# Generated by Django 3.2.16 on 2022-10-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0002_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['created_at']},
        ),
    ]
