# Generated by Django 3.2.16 on 2022-10-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0003_alter_posts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_at']},
        ),
    ]
