# Generated by Django 3.2.16 on 2022-10-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='body_comment',
        ),
    ]
